# Generated by Django 5.1.2 on 2024-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('loan_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_amnt', models.FloatField()),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_acno', models.IntegerField()),
            ],
        ),
    ]
